name: Update CN Domains

on:
  schedule:
    - cron: '0 6 * * *'  # 每天 UTC 时间 6:00 运行
  workflow_dispatch:  # 手动触发工作流

jobs:
  update_cn_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download accelerated-domains.china.conf
      run: |
        curl -o accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/accelerated-domains.china.conf

    - name: Extract domains and save to cn-domains.txt
      run: |
        # 提取加速域名并存入 cn-domains.txt
        grep -oP '(?<=/).*?(?=/)' accelerated-domains.china.conf > cn-domains.txt

    - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "⌚️$(date +%Y%m%d%H%M%S)"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_ENV
          fi
        shell: bash

    - name: Push changes
        if: env.changes == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
        shell: bash
