name: Update CN Domains

on:
  schedule:
    - cron: '0 6 * * *'  # 每天 UTC 时间 6:00 运行
  workflow_dispatch:  # 手动触发工作流

jobs:
  update_cn_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download gfw.txt
      run: |
        curl -o gfw.txt https://raw.githubusercontent.com/ruijzhan/chnroute/refs/heads/master/gfwlist.txt
    
    - name: Add 'domain:' prefix to gfw.txt
      run: |
        # 在 gfw.txt 的每行前添加 'full:' 前缀
        sed -i 's/^/domain:/' gfw.txt
   

    - name: Download accelerated-domains.china.conf
      run: |
        curl -o accelerated-domains.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/accelerated-domains.china.conf

    - name: Extract domains and save to cn-domains.txt
      run: |
        # 提取加速域名并存入 cn-domains.txt
        grep -oP '(?<=/).*?(?=/)' accelerated-domains.china.conf | sed 's/^/full:/' > cn-domains.txt

    - name: Download apple.china.conf
      run: |
        curl -o apple.china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/refs/heads/master/apple.china.conf

    - name: Extract domains and save to apple.txt
      run: |
        # 提取apple域名并存入 apple.txt
        grep -oP '(?<=/).*?(?=/)' apple.china.conf | sed 's/^/full:/' > apple.txt

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 添加所有更改的文件，包括新下载的文件
        git add .
        
        # 检查是否有更改需要提交
        if [ -n "$(git status --porcelain)" ]; then
          git add cn-domains.txt
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
        else
          echo "No changes to commit."
        fi  # 结束 if 语句
